import { createContext,useContext,useEffect,useMemo,useState,type FormEvent,type ReactNode } from 'react';
import type { Session } from '@supabase/supabase-js';
import { setApiAccessToken } from '../api/client';
import { hasSupabaseConfig,supabase } from '../lib/supabase';

type AuthValue={session:Session|null;loading:boolean;signOut:()=>Promise<void>};
const AuthContext=createContext<AuthValue>({session:null,loading:true,signOut:async()=>{}});
export const useAuth=()=>useContext(AuthContext);
export function AuthProvider({children}:{children:ReactNode}){const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{if(!supabase){setLoading(false);return}void supabase.auth.getSession().then(({data})=>{setSession(data.session);setApiAccessToken(data.session?.access_token);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setApiAccessToken(next?.access_token)});return()=>data.subscription.unsubscribe()},[]);const value=useMemo(()=>({session,loading,signOut:async()=>{await supabase?.auth.signOut()}}),[session,loading]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function SignIn(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(event:FormEvent){event.preventDefault();if(!supabase)return;setBusy(true);setError('');const{error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError)setError(authError.message);setBusy(false)}if(!hasSupabaseConfig)return <main className="center-card"><h1>VC Brain Test UI</h1><p className="error">Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.</p></main>;return <main className="center-card"><h1>VC Brain Test UI</h1><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></main>}
