import { createFileRoute } from '@tanstack/react-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { diligenceApi } from '@/api/diligence';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { StatusBadge, formatDate } from '@/components/vc/primitives';

export const Route=createFileRoute('/diligence/$token')({component:FounderDiligencePortal,head:()=>({meta:[{title:'Secure diligence portal — VC Mind'},{name:'robots',content:'noindex,nofollow'}]})});
function FounderDiligencePortal(){const{token}=Route.useParams();const qc=useQueryClient();const portal=useQuery({queryKey:['founder-diligence',token],queryFn:()=>diligenceApi.get(token),refetchInterval:5000,retry:false});const [busy,setBusy]=useState('');const [messages,setMessages]=useState<Record<string,string>>({});const refresh=()=>qc.invalidateQueries({queryKey:['founder-diligence',token]});
 if(portal.isLoading)return <main className="grid min-h-dvh place-items-center bg-background"><p className="text-sm text-muted-foreground">Loading secure diligence requests…</p></main>;
 if(portal.error)return <main className="grid min-h-dvh place-items-center bg-background px-4"><div className="max-w-md rounded-lg border bg-card p-6 text-center"><h1 className="font-semibold">This access link is unavailable</h1><p className="mt-2 text-sm text-muted-foreground">It may be invalid, expired, or revoked. Ask your investor contact for a new link.</p></div></main>;
 const data=portal.data!;return <main className="min-h-dvh bg-muted/30 px-4 py-10"><div className="mx-auto max-w-3xl"><header className="mb-6"><div className="text-sm font-semibold">VC Mind · Secure diligence portal</div><h1 className="mt-2 text-2xl font-semibold">Information requests for {data.application.companyName}</h1><p className="mt-2 text-sm text-muted-foreground">Upload only the documents requested below. Files are stored privately and reviewed by the assigned investment team.</p></header><div className="space-y-4">{data.requests.map(r=>{const doc=data.submissions.documents.find(d=>d.information_request_id===r.id);const responded=data.submissions.responses.some(x=>x.information_request_id===r.id);return <section key={r.id} className="rounded-lg border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-medium">{r.title}</h2><p className="mt-1 text-sm text-muted-foreground">{r.description}</p></div><StatusBadge value={doc?.processing_status??(responded?'submitted':r.status)}/></div><div className="mt-3 text-xs text-muted-foreground">Required type: {r.requested_document_type?.replaceAll('_',' ')??'text response or other document'} · Due: {r.due_at?formatDate(r.due_at):'No due date'}</div>{r.requested_document_type&&<div className="mt-4"><input aria-label={`Upload ${r.title}`} type="file" accept=".pdf,.csv,.xlsx" disabled={busy===r.id} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(r.id);setMessages(m=>({...m,[r.id]:''}));try{await diligenceApi.upload(token,r.id,r.requested_document_type!,file);setMessages(m=>({...m,[r.id]:'Upload received and queued for secure processing.'}));await refresh()}catch(err){setMessages(m=>({...m,[r.id]:err instanceof Error?err.message:'Upload failed.'}))}finally{setBusy('')}}}/>{doc&&<p className="mt-2 text-xs">{doc.original_filename} · {doc.processing_status}</p>}</div>}<form className="mt-4 space-y-2" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);const response=String(form.get('response')??'');setBusy(r.id);try{await diligenceApi.respond(token,r.id,response);setMessages(m=>({...m,[r.id]:'Response submitted.'}));await refresh()}catch(err){setMessages(m=>({...m,[r.id]:err instanceof Error?err.message:'Submission failed.'}))}finally{setBusy('')}}}><Textarea name="response" maxLength={10000} placeholder="Optional text response"/><Button size="sm" disabled={busy===r.id}>Submit response</Button></form>{messages[r.id]&&<p role="status" className="mt-3 text-xs text-primary">{messages[r.id]}</p>}</section>})}{!data.requests.length&&<div className="rounded-lg border bg-card p-6 text-sm text-muted-foreground">There are no open information requests.</div>}</div></div></main>}
