import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { applicationsApi } from '@/api/applications';
import { Button } from '@/components/ui/button';
import { Panel, StatusBadge, formatDate } from './primitives';

export function PrivateDiligencePanel({applicationId}:{applicationId:string}){
 const qc=useQueryClient();const [link,setLink]=useState('');const docs=useQuery({queryKey:['private-documents',applicationId],queryFn:()=>applicationsApi.privateDocuments(applicationId)});const recs=useQuery({queryKey:['reconciliations',applicationId],queryFn:()=>applicationsApi.reconciliations(applicationId)});const closing=useQuery({queryKey:['closing',applicationId],queryFn:()=>applicationsApi.closingReadiness(applicationId)});
 const refresh=()=>qc.invalidateQueries({predicate:q=>Array.isArray(q.queryKey)&&q.queryKey.includes(applicationId)});
 return <div className="space-y-4">
  <Panel title="Founder access"><div className="flex flex-wrap gap-2"><Button size="sm" onClick={async()=>{const r=await applicationsApi.createDiligenceAccess(applicationId);setLink(`${location.origin}/diligence/${r.token}`)}}>Create secure link</Button><Button size="sm" variant="outline" onClick={async()=>{await applicationsApi.revokeDiligenceAccess(applicationId);setLink('')}}>Revoke links</Button><Button size="sm" variant="outline" onClick={async()=>{await applicationsApi.reconcile(applicationId);await refresh()}}>Reconcile</Button><Button size="sm" variant="outline" onClick={async()=>{await applicationsApi.reunderwrite(applicationId);await refresh()}}>Re-underwrite</Button></div>{link&&<div className="mt-3 rounded border bg-muted p-3 text-xs"><p>Copy this link now. The raw token is not stored and will not be shown again.</p><a className="mt-1 block break-all text-primary" href={link}>{link}</a></div>}</Panel>
  <Panel title="Private documents"><div className="space-y-2">{docs.data?.map(d=><div key={d.id} className="flex items-center justify-between rounded border p-3 text-sm"><div><div>{d.original_filename??d.document_type}</div><div className="text-xs text-muted-foreground">{d.document_type.replaceAll('_',' ')} · {formatDate(d.uploaded_at)} · extraction {d.document_extractions.find(e=>e.is_current)?.confidence??'—'}</div></div><div className="flex items-center gap-2"><StatusBadge value={d.processing_status}/>{d.downloadUrl&&<a className="text-xs text-primary" href={d.downloadUrl}>Download</a>}</div></div>)}{!docs.data?.length&&<p className="text-sm text-muted-foreground">No private documents uploaded.</p>}</div></Panel>
  <Panel title="Claim reconciliations"><div className="space-y-2">{recs.data?.map(r=><div key={r.id} className={`rounded border p-3 text-sm ${r.material?'border-destructive/40':''}`}><div className="flex justify-between gap-2"><span>{r.claims?.claim_text}</span><StatusBadge value={r.result}/></div><p className="mt-1 text-xs text-muted-foreground">{r.severity} · {r.explanation}</p></div>)}{!recs.data?.length&&<p className="text-sm text-muted-foreground">No reconciliations yet.</p>}</div></Panel>
  <Panel title="Closing readiness"><div className="mb-3 flex items-center gap-2"><StatusBadge value={closing.data?.state}/><span className="text-xs text-muted-foreground">{closing.data?.disclaimer}</span></div><div className="grid gap-2 sm:grid-cols-2">{closing.data?.items.map(i=><label key={i.id} className="flex items-center gap-2 rounded border p-2 text-xs"><input type="checkbox" checked={['completed','waived'].includes(i.status)} onChange={async e=>{await applicationsApi.updateClosingItem(applicationId,i.id,{status:e.target.checked?'completed':'not_started'});await refresh()}}/><span>{i.check_type.replaceAll('_',' ')}</span>{i.blocking&&<span className="text-destructive">blocking</span>}</label>)}</div></Panel>
 </div>;
}
