import type { ClosingCheckStatus } from '../../types/database.js';
import { AppError } from '../../lib/errors.js';
import type { AuthContext } from '../auth.js';
import { assertApplicationAccess, requireRoles } from '../auth.js';
import { getServiceClient } from '../supabase.js';

export const CLOSING_CHECKS = ['thesis_approved','founder_identity_reviewed','incorporation_verified','cap_table_reviewed','existing_safes_disclosed','revenue_evidence_reviewed','customer_concentration_reviewed','deal_terms_approved','critical_contradictions_resolved','memo_approved','human_decision_recorded'] as const;
const blocking=new Set(['founder_identity_reviewed','incorporation_verified','cap_table_reviewed','existing_safes_disclosed','critical_contradictions_resolved','human_decision_recorded']);
export function closingState(recommendation:string|null,decision:string|null,items:Array<{status:ClosingCheckStatus;blocking:boolean}>){
  if(recommendation==='pass'||decision==='passed')return 'pass' as const;if(items.some(i=>i.blocking&&(i.status==='blocked'||!['completed','waived'].includes(i.status))))return 'blocked' as const;
  const complete=items.length===CLOSING_CHECKS.length&&items.every(i=>['completed','waived'].includes(i.status));if(decision==='approved'&&complete)return 'ready_for_closing' as const;if(['approved','conditional_approval'].includes(decision??''))return 'conditional_approval' as const;return 'blocked' as const;
}
export class ClosingReadinessService{
  async calculate(applicationId:string){const db=getServiceClient();for(const checkType of CLOSING_CHECKS)await db.from('closing_checklist_items').upsert({application_id:applicationId,check_type:checkType,blocking:blocking.has(checkType)},{onConflict:'application_id,check_type',ignoreDuplicates:true});const [{data:application},{data:decision},{data:items}]=await Promise.all([db.from('applications').select('recommendation').eq('id',applicationId).single(),db.from('decisions').select('decision').eq('application_id',applicationId).eq('is_current',true).maybeSingle(),db.from('closing_checklist_items').select('*').eq('application_id',applicationId).order('created_at')]);return {state:closingState(application?.recommendation??null,decision?.decision??null,items??[]),recommendation:application?.recommendation??null,humanDecision:decision?.decision??null,items:items??[],disclaimer:'Readiness is an internal diligence state, not legal closing approval.'};}
  async get(applicationId:string,auth:AuthContext){await assertApplicationAccess(auth,applicationId);return this.calculate(applicationId);}
  async update(applicationId:string,itemId:string,input:{status:ClosingCheckStatus;blocking?:boolean|undefined;notes?:string|undefined;evidenceDocumentId?:string|undefined},auth:AuthContext){requireRoles(auth,['admin','investment_manager','analyst']);await assertApplicationAccess(auth,applicationId);const db=getServiceClient();if(input.evidenceDocumentId){const{data}=await db.from('documents').select('id').eq('id',input.evidenceDocumentId).eq('application_id',applicationId).single();if(!data)throw new AppError('VALIDATION_ERROR','Evidence document belongs to another application',400);}const update={status:input.status,reviewed_by:auth.userId,reviewed_at:new Date().toISOString(),...(input.blocking!==undefined?{blocking:input.blocking}:{}),...(input.notes!==undefined?{notes:input.notes}:{}),...(input.evidenceDocumentId!==undefined?{evidence_document_id:input.evidenceDocumentId}:{})};const {data,error}=await db.from('closing_checklist_items').update(update).eq('id',itemId).eq('application_id',applicationId).select('*').single();if(error||!data)throw new AppError('NOT_FOUND','Closing checklist item not found',404);return {item:data,readiness:await this.calculate(applicationId)};}
}
