import { AppError } from '../../lib/errors.js';
import type { ScoreDimension } from '../../types/database.js';
import { calculateEvidenceCoverage } from '../evidence/evidence-coverage.js';
import { dimensionScore,factorPoints,type FactorAssessmentLevel,type FactorDimension } from '../scoring/factor-scoring.js';
import { recommend } from '../scoring/recommendation.service.js';
import { RECOMMENDATION_POLICY,SCORE_WEIGHTS,SCORING_VERSION } from '../scoring/scoring.config.js';
import { hasCriticalContradiction,overallScore } from '../scoring/scoring.service.js';
import { getServiceClient } from '../supabase.js';

export const AFFECTED_DIMENSIONS:Record<string,ScoreDimension[]>={revenue_export:['traction','deal_economics','risk_resilience'],bank_statement:['traction','risk_resilience'],cap_table:['deal_economics','risk_resilience'],safe_agreement:['deal_economics','risk_resilience'],term_sheet:['deal_economics','risk_resilience'],customer_contract:['traction','risk_resilience'],customer_list:['traction','risk_resilience'],retention_report:['traction','risk_resilience'],product_analytics:['product','traction'],incorporation_document:['risk_resilience'],identity_document:['risk_resilience'],debt_schedule:['deal_economics','risk_resilience'],financial_model:['traction','deal_economics','risk_resilience'],other:['risk_resilience']};
const levels:FactorAssessmentLevel[]=['none','weak','moderate','strong','exceptional'];
export function shiftAssessmentLevel(level:FactorAssessmentLevel,steps:number):FactorAssessmentLevel{return levels[Math.max(0,Math.min(levels.length-1,levels.indexOf(level)+steps))]!;}

export class SelectiveReunderwritingService{
 async recalculate(applicationId:string,documentId?:string){
  const db=getServiceClient();
  const [{data:docs},{data:current},{data:currentFactors},{data:claims},{data:reconciliations}]=await Promise.all([
   documentId?db.from('documents').select('document_type').eq('id',documentId).eq('application_id',applicationId):db.from('documents').select('document_type').eq('application_id',applicationId).neq('document_type','pitch_deck'),
   db.from('scores').select('*').eq('application_id',applicationId).eq('is_current',true),
   db.from('score_factors').select('*').eq('application_id',applicationId).eq('is_current',true),
   db.from('claims').select('importance,verification_status,category,checkable').eq('application_id',applicationId),
   db.from('claim_reconciliations').select('result,material,severity').eq('application_id',applicationId).eq('is_current',true)
  ]);
  const affected=new Set((docs??[]).flatMap(document=>AFFECTED_DIMENSIONS[document.document_type]??[]).filter((dimension):dimension is FactorDimension=>dimension!=='overall'));
  const currentMap=new Map((current??[]).map(score=>[score.dimension,Number(score.score)]));
  const matches=(reconciliations??[]).filter(row=>['matched','approximately_matched'].includes(row.result)).length;const mismatches=(reconciliations??[]).filter(row=>row.material).length;const steps=mismatches>0?-1:matches>0?1:0;const updatedFactors:string[]=[];
  for(const dimension of affected){const factors=(currentFactors??[]).filter(factor=>factor.dimension===dimension);if(!factors.length)continue;const next=factors.map(factor=>{const level=shiftAssessmentLevel(factor.assessment_level,steps);const missingData=mismatches>0?true:matches>0?false:factor.missing_data;return{factor,level,missingData,score:factorPoints(Number(factor.maximum_score),{level,missingData})};});const score=dimensionScore(next.map(item=>({score:item.score,maximumScore:Number(item.factor.maximum_score)})));const weight=SCORE_WEIGHTS[dimension];const{data:scoreRow,error}=await db.from('scores').insert({application_id:applicationId,dimension,score,weight,weighted_score:score*weight,explanation:`Derived from updated factors after private reconciliation (${matches} matches, ${mismatches} material mismatches).`,evidence_count:matches+mismatches,scoring_version:`${SCORING_VERSION}-private-v1`}).select('id').single();if(error||!scoreRow)throw new AppError('INTERNAL_ERROR','Affected score could not be stored',500,{database:error?.message});const{error:factorError}=await db.from('score_factors').insert(next.map(item=>({application_id:applicationId,score_id:scoreRow.id,dimension,factor_key:item.factor.factor_key,factor_label:item.factor.factor_label,assessment_level:item.level,score:item.score,maximum_score:item.factor.maximum_score,explanation:`${item.factor.explanation} Reassessed deterministically from private-document reconciliation.`,supporting_claim_ids:item.factor.supporting_claim_ids,supporting_evidence_ids:item.factor.supporting_evidence_ids,missing_data:item.missingData,rubric_version:`${SCORING_VERSION}-private-v1`,model_run_id:null})));if(factorError)throw new AppError('INTERNAL_ERROR','Affected factor history could not be stored',500,{database:factorError.message});currentMap.set(dimension,score);updatedFactors.push(...next.map(item=>`${dimension}:${item.factor.factor_key}`));}
  const dimensions={founder:currentMap.get('founder')??0,market:currentMap.get('market')??0,traction:currentMap.get('traction')??0,product:currentMap.get('product')??0,thesis_fit:currentMap.get('thesis_fit')??0,deal_economics:currentMap.get('deal_economics')??0,risk_resilience:currentMap.get('risk_resilience')??0};const overall=overallScore(dimensions);const coverage=calculateEvidenceCoverage(claims??[]);const critical=(reconciliations??[]).some(row=>row.material&&row.severity==='critical')||hasCriticalContradiction(claims??[]);const recommendation=recommend({scores:dimensions,overall,evidenceCoverage:coverage.coveragePercentage,hasCheckableClaims:coverage.hasCheckableClaims,hardThesisFailure:dimensions.thesis_fit<5,criticalContradiction:critical,unresolvedBlockingRisk:(claims??[]).some(claim=>claim.importance==='critical'&&['unverified','partially_verified'].includes(claim.verification_status)),unacceptableDealEconomics:dimensions.deal_economics<3,materialDataInconsistency:(reconciliations??[]).filter(row=>row.material).length>=2,incompleteCriticalDiligence:(claims??[]).some(claim=>claim.importance==='critical'&&claim.verification_status==='unverified'),missingPrivateTractionValidation:!(claims??[]).some(claim=>claim.category==='traction'&&claim.verification_status==='verified'),missingDealTerms:!(claims??[]).some(claim=>claim.category==='deal_terms'&&claim.verification_status==='verified')});
  await db.from('scores').insert({application_id:applicationId,dimension:'overall',score:overall,weight:1,weighted_score:overall,explanation:recommendation.explanation,evidence_count:matches+mismatches,scoring_version:`${SCORING_VERSION}-private-v1`});await db.from('applications').update({investment_score:overall,evidence_coverage:coverage.coveragePercentage,recommendation:recommendation.recommendation,recommendation_policy_version:RECOMMENDATION_POLICY.version,recommendation_policy_calibrated:RECOMMENDATION_POLICY.calibrated}).eq('id',applicationId);
  return{affectedDimensions:[...affected],updatedFactors,overall,evidenceCoverage:coverage.coveragePercentage,recommendation};
 }
}
