export type Stage = 'submitted'|'extracting'|'claims_ready'|'screened'|'diligence_running'|'evidence_ready'|'memo_draft'|'memo_ready'|'approved'|'passed'|'needs_more_info'|'failed';
export type Recommendation = 'invest'|'pass'|'needs_more_info';
export type Json = string|number|boolean|null|Json[]|{[key:string]:Json|undefined};
export interface ApiErrorBody { error?: { code?: string; message?: string; details?: unknown; requestId?: string } }
export interface DebugEntry { method:string; path:string; status:number; errorCode?:string; message?:string; requestId?:string; response:unknown }
export interface ApplicationSummary { application_id:string;company_name:string;current_stage:Stage;recommendation:Recommendation|null;investment_score:number|null;calculated_evidence_coverage:number;submitted_at:string;decision_deadline:string;remaining_sla_time:string;current_memo_id:string|null;current_decision:string|null;open_information_requests:number }
export interface Application { id:string;current_stage:Stage;recommendation:Recommendation|null;investment_score:number|null;evidence_coverage:number|null;decision_deadline:string;submitted_at:string;failure_reason:string|null;companies:{name:string;website_url:string|null;sector:string|null;stage:string|null;geography:string|null;product_description:string|null};application_founders:Array<{role_at_submission:string|null;is_primary_contact:boolean;founders:{full_name:string;email:string|null;linkedin_url:string|null;github_url:string|null}}> }
export interface Job { id:string;job_type:string;stage:Stage|null;status:'pending'|'running'|'completed'|'failed'|'cancelled';attempt_number:number;started_at:string|null;completed_at:string|null;error_message:string|null;created_at:string }
export interface ApplicationStatus { applicationId:string;current_stage:Stage;failure_reason:string|null;jobs:Job[] }
export interface StageEvent { id:string;stage:Stage;status:string;started_at:string|null;completed_at:string|null;duration_ms:number|null;attempt_number:number;error_message:string|null;created_at:string }
export interface Claim { id:string;claim_text:string;category:string;importance:string;checkable:boolean;verification_status:string;evidence_confidence:number|null;source_excerpt:string|null;document_page_id:string|null }
export interface EvidenceSource { source_title:string|null;source_domain:string|null;canonical_url:string;founder_controlled:boolean;authoritative_source:boolean;snapshot_text?:string|null }
export interface Evidence { id:string;claim_id:string;relationship:string;excerpt:string;source_quality:number|null;entity_match:number|null;validation_status:'pending'|'valid'|'invalid';validation_error:string|null;evidence_sources:EvidenceSource }
export interface Score { id:string;dimension:string;score:number;weight:number;weighted_score:number;evidence_count:number;explanation:string|null;scoring_version:string;is_current:boolean }
export interface MemoClaim { claimId?:string;summary?:string;evidence?:Array<{evidenceId:string;evidenceSourceId:string;excerpt:string}> }
export interface ValidationFlag { type?:string;severity?:string;message?:string;claimId?:string;evidenceId?:string }
export interface Memo { id:string;version:number;investment_hypothesis:string|null;thesis_alignment:string|null;strengths:Json;weaknesses:Json;opportunities:Json;threats:Json;verified_claims:Json;unverified_claims:Json;contradicted_claims:Json;key_questions:Json;strongest_reason_to_pass:string|null;recommendation:Recommendation;recommendation_reason:string|null;confidence:number|null;validation_flags:Json;is_current:boolean;created_at:string }
export interface InformationRequest { id:string;claim_id:string|null;title:string;description:string|null;requested_document_type:string|null;status:string;due_at:string|null }
export interface Decision { id:string;decision:string;decision_reason:string|null;created_at:string;is_current:boolean }
export interface Thesis { id:string;name:string;version:number;is_active:boolean;description:string|null }
export interface CreateApplicationPayload { company:{name:string;websiteUrl?:string;sector?:string;stage?:string;geography?:string;productDescription?:string};founders:Array<{fullName:string;email?:string;linkedinUrl?:string;githubUrl?:string;role?:string;isPrimaryContact?:boolean}>;thesisConfigId:string;fundingAskUsd?:number;valuationCapUsd?:number;preMoneyValuationUsd?:number }
