export type Stage = 'submitted'|'extracting'|'claims_ready'|'screened'|'diligence_running'|'evidence_ready'|'memo_draft'|'memo_ready'|'approved'|'passed'|'needs_more_info'|'failed';
export type Recommendation = 'invest'|'pass'|'needs_more_info';
export type Json = string|number|boolean|null|Json[]|{[key:string]:Json|undefined};
export interface ApiErrorBody { error?: { code?: string; message?: string; details?: unknown; requestId?: string } }
export interface DebugEntry { method:string; path:string; status:number; errorCode?:string; message?:string; requestId?:string; response:unknown }
export interface ApplicationSummary { application_id:string;company_name:string;current_stage:Stage;recommendation:Recommendation|null;investment_score:number|null;calculated_evidence_coverage:number;submitted_at:string;decision_deadline:string;remaining_sla_time:string;current_memo_id:string|null;current_decision:string|null;open_information_requests:number }
export interface Application { id:string;current_stage:Stage;recommendation:Recommendation|null;recommendation_policy_version:string|null;recommendation_policy_calibrated:boolean|null;investment_score:number|null;evidence_coverage:number|null;decision_deadline:string;submitted_at:string;failure_reason:string|null;companies:{name:string;website_url:string|null;sector:string|null;stage:string|null;geography:string|null;product_description:string|null};application_founders:Array<{role_at_submission:string|null;is_primary_contact:boolean;founders:{full_name:string;email:string|null;linkedin_url:string|null;github_url:string|null}}> }
export interface Job { id:string;job_type:string;stage:Stage|null;status:'pending'|'running'|'completed'|'failed'|'cancelled';attempt_number:number;started_at:string|null;completed_at:string|null;error_message:string|null;created_at:string }
export interface ApplicationStatus { applicationId:string;current_stage:Stage;failure_reason:string|null;jobs:Job[] }
export interface StageEvent { id:string;stage:Stage;status:string;started_at:string|null;completed_at:string|null;duration_ms:number|null;attempt_number:number;error_message:string|null;created_at:string }
export interface Claim { id:string;claim_text:string;category:string;importance:string;checkable:boolean;verification_status:string;evidence_confidence:number|null;source_excerpt:string|null;document_page_id:string|null }
export interface EvidenceSource { source_title:string|null;source_domain:string|null;canonical_url:string;founder_controlled:boolean;authoritative_source:boolean;snapshot_text?:string|null;independence_cluster:string|null;cluster_reason:string|null;cluster_similarity:number|null;original_publisher:string|null;counts_as_independent:boolean }
export interface Evidence { id:string;claim_id:string;relationship:string;excerpt:string;source_quality:number|null;entity_match:number|null;validation_status:'pending'|'valid'|'invalid';validation_error:string|null;evidence_sources:EvidenceSource }
export interface Score { id:string;dimension:string;score:number;weight:number;weighted_score:number;evidence_count:number;explanation:string|null;scoring_version:string;is_current:boolean }
export interface ScoreFactor {id:string;dimension:string;factor_key:string;factor_label:string;assessment_level:'none'|'weak'|'moderate'|'strong'|'exceptional';score:number;maximum_score:number;explanation:string;supporting_claim_ids:string[];supporting_evidence_ids:string[];missing_data:boolean;rubric_version:string;is_current:boolean}
export interface StageSLA {stage:string;budget_seconds:number;elapsed_seconds:number;remaining_seconds:number;budget_used_percentage:number;sla_status:'on_track'|'at_risk'|'breached'|'completed';started_at:string|null;completed_at:string|null;attempt_number:number;fallback_actions:string[]}
export interface ApplicationSLA {deadline:string;totalElapsedSeconds:number;totalRemainingSeconds:number;status:'on_track'|'at_risk'|'breached'|'completed';currentStage:string;currentStageBudgetSeconds:number;currentStageElapsedSeconds:number;currentStageBudgetUsedPercentage:number;blockingReasons:string[];fallbackActions:string[];stages:StageSLA[]}
export interface AIModelRun {id:string;provider:string;model_name:string;prompt_version:string;status:string;is_fallback:boolean;fallback_reason:string|null;latency_ms:number|null;created_at:string}
export interface MemoClaim { claimId?:string;summary?:string;evidence?:Array<{evidenceId:string;evidenceSourceId:string;excerpt:string}> }
export interface ValidationFlag { type?:string;severity?:string;message?:string;claimId?:string;evidenceId?:string }
export interface Memo { id:string;version:number;investment_hypothesis:string|null;thesis_alignment:string|null;strengths:Json;weaknesses:Json;opportunities:Json;threats:Json;verified_claims:Json;unverified_claims:Json;contradicted_claims:Json;key_questions:Json;strongest_reason_to_pass:string|null;recommendation:Recommendation;recommendation_reason:string|null;recommendation_policy_version:string|null;recommendation_policy_calibrated:boolean|null;confidence:number|null;validation_flags:Json;is_current:boolean;created_at:string }
export interface InformationRequest { id:string;claim_id:string|null;title:string;description:string|null;requested_document_type:string|null;status:string;due_at:string|null }
export interface Decision { id:string;decision:string;decision_reason:string|null;created_at:string;is_current:boolean }
export interface Thesis { id:string;name:string;version:number;is_active:boolean;description:string|null }
export interface CreateApplicationPayload { company:{name:string;websiteUrl?:string;sector?:string;stage?:string;geography?:string;productDescription?:string};founders:Array<{fullName:string;email?:string;linkedinUrl?:string;githubUrl?:string;role?:string;isPrimaryContact?:boolean}>;thesisConfigId:string;fundingAskUsd?:number;valuationCapUsd?:number;preMoneyValuationUsd?:number }
export interface PrivateDocument {id:string;information_request_id:string|null;document_type:string;original_filename:string|null;mime_type:string|null;file_size_bytes:number|null;processing_status:string;authenticity_status:string;manual_review_status:string;uploaded_at:string;processed_at:string|null;downloadUrl:string|null;document_extractions:Array<{id:string;status:string;confidence:number|null;warnings:Json;is_current:boolean}>}
export interface Reconciliation {id:string;claim_id:string;result:string;variance_percentage:number|null;material:boolean;severity:string;explanation:string;supporting_document_ids:string[];is_current:boolean;created_at:string;claims:{claim_text:string;category:string;importance:string}}
export interface ClosingItem {id:string;check_type:string;status:'not_started'|'in_progress'|'completed'|'waived'|'blocked';blocking:boolean;notes:string|null;evidence_document_id:string|null}
export interface ClosingReadiness {state:'ready_for_closing'|'conditional_approval'|'blocked'|'pass';recommendation:Recommendation|null;humanDecision:string|null;items:ClosingItem[];disclaimer:string}
export interface FounderPortal {application:{id:string;companyName:string};requests:Array<{id:string;title:string;description:string|null;requested_document_type:string|null;status:string;due_at:string|null;submitted_document_id:string|null}>;submissions:{documents:Array<{id:string;information_request_id:string;document_type:string;original_filename:string;processing_status:string;uploaded_at:string}>;responses:Array<{information_request_id:string;created_at:string}>}}
