import type { FastifyInstance,FastifyRequest } from 'fastify';import { z } from 'zod';import { getEnv } from '../../lib/env.js';import { AppError } from '../../lib/errors.js';import { ApplicationRepository } from '../application/application.repository.js';import { ApplicationService } from '../application/application.service.js';import { authenticate,assertApplicationAccess,requireRoles } from '../auth.js';import { DecisionService } from '../decisions/decision.service.js';import { DiligenceOrchestrator } from '../diligence/diligence.orchestrator.js';import { DocumentService } from '../documents/document.service.js';import { JobRepository } from '../jobs/job.repository.js';import { JobRunner } from '../jobs/job-runner.js';import { getServiceClient } from '../supabase.js';import { ThesisService } from './thesis.js';
const idParams=z.object({id:z.uuid()});const applicationRepo=new ApplicationRepository();
async function auth(request:FastifyRequest){const context=await authenticate(request);request.auth=context;return context;}
export async function registerRoutes(app:FastifyInstance):Promise<void>{
 app.get('/api/health',async()=>({status:'ok',service:'vc-brain-backend',timestamp:new Date().toISOString()}));
 app.post('/api/applications',async(request,reply)=>{const result=await new ApplicationService().create(request.body,await auth(request));return reply.code(201).send(result);});
 app.delete('/api/applications/:id',async(request,reply)=>{const{id}=idParams.parse(request.params);await new ApplicationService().remove(id,await auth(request));return reply.code(204).send();});
 app.get('/api/applications/:id',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);return applicationRepo.get(id);});
 app.get('/api/applications/:id/summary',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);return applicationRepo.summary(id);});
 app.post('/api/applications/:id/pitch-deck',async(request,reply)=>{const{id}=idParams.parse(request.params);const a=await auth(request);const file=await request.file();if(!file)throw new AppError('VALIDATION_ERROR','Multipart PDF file is required',400);const buffer=await file.toBuffer();const document=await new DocumentService().uploadPitchDeck(id,{filename:file.filename,mimetype:file.mimetype,buffer},a);return reply.code(201).send(document);});
 app.post('/api/applications/:id/run-diligence',async(request,reply)=>{const{id}=idParams.parse(request.params);return reply.code(202).send(await new DiligenceOrchestrator().runFullDiligence(id,await auth(request)));});
 app.post('/api/applications/:id/resume',async(request,reply)=>{const{id}=idParams.parse(request.params);return reply.code(202).send(await new DiligenceOrchestrator().resume(id,await auth(request)));});
 app.get('/api/applications/:id/status',async(request)=>{const{id}=idParams.parse(request.params);return new DiligenceOrchestrator().status(id,await auth(request));});
 for(const [path,table] of Object.entries({claims:'claims',evidence:'evidence',scores:'scores',memos:'memos','information-requests':'information_requests',decisions:'decisions'} as const))app.get(`/api/applications/:id/${path}`,async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);return applicationRepo.related(table,id);});
 app.post('/api/applications/:id/decisions',async(request,reply)=>{const{id}=idParams.parse(request.params);return reply.code(201).send(await new DecisionService().record(id,request.body,await auth(request)));});
 app.get('/api/jobs/:id',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);const{data}=await getServiceClient().from('processing_jobs').select('*').eq('id',id).single();if(!data)throw new AppError('NOT_FOUND','Job not found',404);await assertApplicationAccess(a,data.application_id);return data;});
 app.post('/api/jobs/:id/retry',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);requireRoles(a,['admin','investment_manager','analyst']);const{data}=await getServiceClient().from('processing_jobs').select('application_id').eq('id',id).single();if(!data)throw new AppError('NOT_FOUND','Job not found',404);await assertApplicationAccess(a,data.application_id);return new JobRepository().retry(id);});
 app.post('/api/jobs/run-next',async(request,reply)=>{const token=request.headers['x-worker-token'];if(typeof token!=='string'||token!==getEnv().INTERNAL_WORKER_TOKEN)throw new AppError('UNAUTHORIZED','Valid worker token required',401);return reply.code(202).send({job:await new JobRunner().runNext()});});
 const thesis=new ThesisService();app.get('/api/thesis',async(request)=>thesis.list(await auth(request)));app.get('/api/thesis/:id',async(request)=>thesis.get(idParams.parse(request.params).id,await auth(request)));app.post('/api/thesis',async(request,reply)=>reply.code(201).send(await thesis.create(request.body,await auth(request))));app.patch('/api/thesis/:id',async(request)=>thesis.revise(idParams.parse(request.params).id,request.body,await auth(request)));
}
