import type { FastifyInstance,FastifyRequest } from 'fastify';import { z } from 'zod';import { getEnv } from '../../lib/env.js';import { AppError } from '../../lib/errors.js';import { ApplicationRepository } from '../application/application.repository.js';import { ApplicationService } from '../application/application.service.js';import { authenticate,assertApplicationAccess,requireRoles } from '../auth.js';import { DecisionService } from '../decisions/decision.service.js';import { DiligenceOrchestrator } from '../diligence/diligence.orchestrator.js';import { DocumentService } from '../documents/document.service.js';import { JobRepository } from '../jobs/job.repository.js';import { JobRunner } from '../jobs/job-runner.js';import { jobDispatcher } from '../jobs/job-dispatcher.js';import { getServiceClient } from '../supabase.js';import { DiligenceAccessService } from '../private-diligence/access-token.service.js';import { PrivateDocumentService } from '../private-diligence/private-document.service.js';import { ClosingReadinessService } from '../private-diligence/closing-readiness.service.js';import { SLAService } from '../sla/sla.service.js';import { ThesisService } from './thesis.js';
const idParams=z.object({id:z.uuid()});const applicationRepo=new ApplicationRepository();
async function auth(request:FastifyRequest){const context=await authenticate(request);request.auth=context;return context;}
export async function registerRoutes(app:FastifyInstance):Promise<void>{
 app.get('/api/health',async()=>({status:'ok',service:'vc-brain-backend',timestamp:new Date().toISOString()}));
 app.post('/api/applications',async(request,reply)=>{const result=await new ApplicationService().create(request.body,await auth(request));return reply.code(201).send(result);});
 app.delete('/api/applications/:id',async(request,reply)=>{const{id}=idParams.parse(request.params);await new ApplicationService().remove(id,await auth(request));return reply.code(204).send();});
 app.get('/api/applications/:id',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);return applicationRepo.get(id);});
 app.get('/api/applications/:id/summary',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);return applicationRepo.summary(id);});
 app.post('/api/applications/:id/pitch-deck',async(request,reply)=>{const{id}=idParams.parse(request.params);const a=await auth(request);const file=await request.file();if(!file)throw new AppError('VALIDATION_ERROR','Multipart PDF file is required',400);const buffer=await file.toBuffer();const document=await new DocumentService().uploadPitchDeck(id,{filename:file.filename,mimetype:file.mimetype,buffer},a);return reply.code(201).send(document);});
 app.post('/api/applications/:id/run-diligence',async(request,reply)=>{const{id}=idParams.parse(request.params);return reply.code(202).send(await new DiligenceOrchestrator().runFullDiligence(id,await auth(request)));});
 app.post('/api/applications/:id/cancel-diligence',async(request)=>{const{id}=idParams.parse(request.params);return new DiligenceOrchestrator().cancel(id,await auth(request));});
 app.post('/api/applications/:id/resume',async(request,reply)=>{const{id}=idParams.parse(request.params);return reply.code(202).send(await new DiligenceOrchestrator().resume(id,await auth(request)));});
 app.get('/api/applications/:id/status',async(request)=>{const{id}=idParams.parse(request.params);return new DiligenceOrchestrator().status(id,await auth(request));});
 app.get('/api/applications/:id/sla',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);return new SLAService().get(id);});
 app.get('/api/applications/:id/score-factors',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);const{data,error}=await getServiceClient().from('score_factors').select('*').eq('application_id',id).order('created_at',{ascending:false});if(error)throw new AppError('INTERNAL_ERROR','Score factors could not be loaded',500);return data??[];});
 app.get('/api/applications/:id/export',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);const[application,scores,factors,memos]=await Promise.all([applicationRepo.get(id),applicationRepo.related('scores',id),getServiceClient().from('score_factors').select('*').eq('application_id',id).eq('is_current',true),applicationRepo.related('memos',id)]);return{title:'VC Brain investment report',recommendationWarning:'Experimental MVP Recommendation\n\nThis recommendation uses heuristic thresholds that have not yet been calibrated against historical investment outcomes.',recommendationPolicy:'MVP v1 — uncalibrated',application,scores,scoreFactors:factors.data??[],memos};});
 app.get('/api/applications/:id/model-runs',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);requireRoles(a,['admin','investment_manager','analyst']);await assertApplicationAccess(a,id);if(getEnv().NODE_ENV==='production')throw new AppError('NOT_FOUND','Diagnostics are not available',404);const{data,error}=await getServiceClient().from('model_runs').select('id,provider,model_name,prompt_version,status,is_fallback,fallback_reason,latency_ms,created_at').eq('application_id',id).order('created_at',{ascending:false});if(error)throw new AppError('INTERNAL_ERROR','Model diagnostics could not be loaded',500);return data??[];});
 for(const [path,table] of Object.entries({claims:'claims',evidence:'evidence',scores:'scores',memos:'memos','information-requests':'information_requests',decisions:'decisions'} as const))app.get(`/api/applications/:id/${path}`,async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);return applicationRepo.related(table,id);});
 app.post('/api/applications/:id/decisions',async(request,reply)=>{const{id}=idParams.parse(request.params);return reply.code(201).send(await new DecisionService().record(id,request.body,await auth(request)));});
 app.post('/api/applications/:id/diligence-access',async(request,reply)=>{const{id}=idParams.parse(request.params);const body=z.object({expiresInHours:z.number().int().min(1).max(720).default(168)}).parse(request.body??{});return reply.code(201).send(await new DiligenceAccessService().create(id,await auth(request),body.expiresInHours));});
 app.post('/api/applications/:id/diligence-access/revoke',async(request)=>{const{id}=idParams.parse(request.params);return new DiligenceAccessService().revoke(id,await auth(request));});
 app.get('/api/diligence/:token',async(request)=>{const{token}=z.object({token:z.string().min(32).max(256)}).parse(request.params);return new DiligenceAccessService().portal(token);});
 app.post('/api/diligence/:token/documents',async(request,reply)=>{const{token}=z.object({token:z.string().min(32).max(256)}).parse(request.params);const file=await request.file();if(!file)throw new AppError('VALIDATION_ERROR','A PDF, CSV, or XLSX file is required',400);const fields=file.fields as Record<string,{value?:unknown}>;const requestId=String(fields.requestId?.value??'');const documentType=String(fields.documentType?.value??'');z.uuid().parse(requestId);const buffer=await file.toBuffer();return reply.code(201).send(await new PrivateDocumentService().upload(token,requestId,documentType,{filename:file.filename,mimetype:file.mimetype,buffer}));});
 app.post('/api/diligence/:token/responses',async(request,reply)=>{const{token}=z.object({token:z.string().min(32).max(256)}).parse(request.params);const body=z.object({requestId:z.uuid(),responseText:z.string().trim().min(1).max(10000)}).parse(request.body);return reply.code(201).send(await new DiligenceAccessService().respond(token,body.requestId,body.responseText));});
 app.get('/api/applications/:id/private-documents',async(request)=>{const{id}=idParams.parse(request.params);return new PrivateDocumentService().list(id,await auth(request));});
 app.get('/api/applications/:id/reconciliations',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);await assertApplicationAccess(a,id);const{data,error}=await getServiceClient().from('claim_reconciliations').select('*,claims(claim_text,category,importance)').eq('application_id',id).order('created_at',{ascending:false});if(error)throw new AppError('INTERNAL_ERROR','Reconciliations could not be loaded',500);return data??[];});
 app.post('/api/applications/:id/reconcile',async(request,reply)=>{const{id}=idParams.parse(request.params);const a=await auth(request);requireRoles(a,['admin','investment_manager','analyst']);await assertApplicationAccess(a,id);const job=await new JobRepository().create(id,'reconcile_claims',{},`manual:${Date.now()}`);jobDispatcher.kick();return reply.code(202).send(job);});
 app.post('/api/applications/:id/reunderwrite',async(request,reply)=>{const{id}=idParams.parse(request.params);const a=await auth(request);requireRoles(a,['admin','investment_manager','analyst']);await assertApplicationAccess(a,id);const job=await new JobRepository().create(id,'recalculate_underwriting',{},`manual:${Date.now()}`);jobDispatcher.kick();return reply.code(202).send(job);});
 app.get('/api/applications/:id/closing-readiness',async(request)=>{const{id}=idParams.parse(request.params);return new ClosingReadinessService().get(id,await auth(request));});
 app.patch('/api/applications/:id/closing-checklist/:itemId',async(request)=>{const{id,itemId}=z.object({id:z.uuid(),itemId:z.uuid()}).parse(request.params);const body=z.object({status:z.enum(['not_started','in_progress','completed','waived','blocked']),blocking:z.boolean().optional(),notes:z.string().max(5000).optional(),evidenceDocumentId:z.uuid().optional()}).parse(request.body);return new ClosingReadinessService().update(id,itemId,body,await auth(request));});
 app.get('/api/jobs/:id',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);const{data}=await getServiceClient().from('processing_jobs').select('*').eq('id',id).single();if(!data)throw new AppError('NOT_FOUND','Job not found',404);await assertApplicationAccess(a,data.application_id);return data;});
 app.post('/api/jobs/:id/retry',async(request)=>{const{id}=idParams.parse(request.params);const a=await auth(request);requireRoles(a,['admin','investment_manager','analyst']);const{data}=await getServiceClient().from('processing_jobs').select('application_id').eq('id',id).single();if(!data)throw new AppError('NOT_FOUND','Job not found',404);await assertApplicationAccess(a,data.application_id);return new JobRepository().retry(id);});
 app.post('/api/jobs/run-next',async(request,reply)=>{const token=request.headers['x-worker-token'];if(typeof token!=='string'||token!==getEnv().INTERNAL_WORKER_TOKEN)throw new AppError('UNAUTHORIZED','Valid worker token required',401);return reply.code(202).send({job:await new JobRunner().runNext()});});
 const thesis=new ThesisService();app.get('/api/thesis',async(request)=>thesis.list(await auth(request)));app.get('/api/thesis/:id',async(request)=>thesis.get(idParams.parse(request.params).id,await auth(request)));app.post('/api/thesis',async(request,reply)=>reply.code(201).send(await thesis.create(request.body,await auth(request))));app.patch('/api/thesis/:id',async(request)=>thesis.revise(idParams.parse(request.params).id,request.body,await auth(request)));
}
