import { AppError } from '../lib/errors.js';
import { getEnv } from '../lib/env.js';
import { log } from '../lib/logger.js';
import { GroqProvider } from './client.js';
import { GeminiFallbackProvider } from './gemini-provider.js';
import { PrimaryAIProvider,type AIAttempt,type AIProvider,type AIResult,type GenerateStructuredInput } from './provider.js';

export type CircuitState='closed'|'open'|'half_open';
export class ProviderCircuitBreaker{private failures:number[]=[];private openedAt:number|null=null;private probeInFlight=false;constructor(private readonly now:()=>number=Date.now,private readonly failureThreshold=5,private readonly failureWindowMs=5*60_000,private readonly cooldownMs=2*60_000){}state():CircuitState{if(this.openedAt===null)return'closed';if(this.now()-this.openedAt>=this.cooldownMs)return'half_open';return'open';}allowPrimary():boolean{const state=this.state();if(state==='closed')return true;if(state==='open')return false;if(this.probeInFlight)return false;this.probeInFlight=true;return true;}recordSuccess(){this.failures=[];this.openedAt=null;this.probeInFlight=false;log('info','AI primary circuit closed after success',{service:'ai-circuit-breaker',event:'closed'});}recordTransientFailure(){const now=this.now();this.failures=this.failures.filter(time=>now-time<=this.failureWindowMs);this.failures.push(now);this.probeInFlight=false;if(this.failures.length>=this.failureThreshold){this.openedAt=now;log('warn','AI primary circuit opened',{service:'ai-circuit-breaker',event:'opened',failureCount:this.failures.length,cooldownMs:this.cooldownMs});}}}
export function fallbackReason(error:unknown):string|null{if(!(error instanceof AppError)||error.code!=='AI_PROVIDER_ERROR'||!error.retryable)return null;const status=Number(error.details?.status??error.statusCode);const kind=String(error.details?.kind??'');if(['authentication','authorization','missing_api_key','invalid_input','invalid_prompt','unsupported_schema','safety_rejection','cancelled'].includes(kind))return null;if(status>=400&&status<500&&![408,429].includes(status))return null;if(status===504)return'timeout';if(status===429||kind==='rate_limit')return'rate_limit';if(status>=500)return'provider_unavailable';if(['empty_response','structured_validation','network_error','provider_error'].includes(kind))return kind;return error.retryable?'temporary_network_error':null;}
const attempt=(provider:string,model:string,status:'completed'|'failed',latencyMs:number,isFallback:boolean,extra:Partial<AIAttempt>={}):AIAttempt=>({provider,model,status,latencyMs,isFallback,...extra});
export class ResilientAIProvider implements AIProvider{constructor(private readonly primary:AIProvider,private readonly fallback:AIProvider,private readonly circuit=new ProviderCircuitBreaker()){}async generateStructured<T>(input:GenerateStructuredInput<T>):Promise<AIResult<T>>{const env=getEnv();const attempts:AIAttempt[]=[];let reason:string|null=null;if(this.circuit.allowPrimary()){const started=Date.now();try{const result=await this.primary.generateStructured(input);this.circuit.recordSuccess();attempts.push(attempt(result.provider,result.model,'completed',result.latencyMs,false,{inputTokens:result.inputTokens,outputTokens:result.outputTokens,estimatedCostUsd:result.estimatedCostUsd,validationResult:{valid:true}}));return{...result,attempts};}catch(error){reason=fallbackReason(error);attempts.push(attempt('groq',input.model,'failed',Date.now()-started,false,{errorMessage:error instanceof Error?error.message:'Unknown primary error',validationResult:{valid:false}}));if(reason)this.circuit.recordTransientFailure();if(!reason)throw error;}}else reason='circuit_open';if(!env.AI_FALLBACK_ENABLED||env.AI_MAX_FALLBACK_ATTEMPTS<1)throw new AppError('AI_PROVIDER_ERROR','Primary AI failed and fallback is disabled',503,{kind:reason??'provider_error',attempts},true);const remaining=Number(input.metadata?.remainingStageTimeMs??Number.POSITIVE_INFINITY);if(remaining<=env.AI_FALLBACK_TIMEOUT_MS+env.AI_FALLBACK_PERSISTENCE_BUFFER_MS)throw new AppError('AI_PROVIDER_ERROR','Stage SLA budget is insufficient for AI fallback',503,{kind:'sla_exhausted',attempts},false);const fallbackInput={...input,model:env.AI_FALLBACK_MODEL,timeoutMs:Math.min(input.timeoutMs??env.AI_FALLBACK_TIMEOUT_MS,env.AI_FALLBACK_TIMEOUT_MS)};const started=Date.now();try{const result=await this.fallback.generateStructured(fallbackInput);attempts.push(attempt(result.provider,result.model,'completed',result.latencyMs,true,{fallbackReason:reason??undefined,inputTokens:result.inputTokens,outputTokens:result.outputTokens,estimatedCostUsd:result.estimatedCostUsd,validationResult:{valid:true}}));return{...result,isFallback:true,fallbackReason:reason??undefined,attempts};}catch(error){attempts.push(attempt('google',env.AI_FALLBACK_MODEL,'failed',Date.now()-started,true,{fallbackReason:reason??undefined,errorMessage:error instanceof Error?error.message:'Unknown fallback error',validationResult:{valid:false}}));throw new AppError('AI_PROVIDER_ERROR','Primary and Gemini fallback attempts failed',503,{kind:'fallback_failed',attempts},false);}}}
export const primaryCircuitBreaker=new ProviderCircuitBreaker();
export function createResilientAIProvider():AIProvider{return new ResilientAIProvider(new PrimaryAIProvider(new GroqProvider()),new GeminiFallbackProvider(),primaryCircuitBreaker);}
