import { AppError } from '../../lib/errors.js';
import type { Json, ProcessingJobRow } from '../../types/database.js';
import { getServiceClient } from '../supabase.js';
import type { JobType } from './job.types.js';
import { retryDelayMs } from './retry-policy.js';

export class JobRepository {
  async create(applicationId: string, type: JobType, payload: Json = {}, suffix = 'v1') {
    const key = `${applicationId}:${type}:${suffix}`; const db = getServiceClient();
    const { data: existing } = await db.from('processing_jobs').select('*').eq('idempotency_key', key).maybeSingle();
    if (existing?.status === 'cancelled') {
      const { data: restarted, error: restartError } = await db.from('processing_jobs').update({ status: 'pending', payload, started_at: null, completed_at: null, error_message: null, result: null, retry_count: 0 }).eq('id', existing.id).select('*').single();
      if (restartError || !restarted) throw new AppError('INTERNAL_ERROR', 'Cancelled job could not be restarted', 500, { database: restartError?.message });
      return restarted;
    }
    if (existing) return existing;
    const { data, error } = await db.from('processing_jobs').insert({ application_id: applicationId, job_type: type, status: 'pending', idempotency_key: key, payload }).select('*').single();
    if (error?.code === '23505') { const { data: raced } = await db.from('processing_jobs').select('*').eq('idempotency_key', key).single(); if (raced) return raced; }
    if (error || !data) throw new AppError('INTERNAL_ERROR', 'Job could not be created', 500, { database: error?.message }); return data;
  }
  async claim(): Promise<ProcessingJobRow | null> { const { data, error } = await getServiceClient().rpc('claim_next_processing_job'); if (error) throw new AppError('INTERNAL_ERROR', 'Could not claim job', 500, { database: error.message }); return data; }
  async complete(id: string, result: Json):Promise<boolean> { const { data,error } = await getServiceClient().from('processing_jobs').update({ status: 'completed', result, completed_at: new Date().toISOString(), error_message: null }).eq('id', id).eq('status','running').select('id').maybeSingle(); if (error) throw new AppError('INTERNAL_ERROR', 'Could not complete job', 500); return Boolean(data); }
  async cancelApplication(applicationId:string):Promise<number>{const completedAt=new Date().toISOString();const db=getServiceClient();const{data,error}=await db.from('processing_jobs').update({status:'cancelled',completed_at:completedAt,error_message:'Diligence stopped by user'}).eq('application_id',applicationId).in('status',['pending','running']).select('id');if(error)throw new AppError('INTERNAL_ERROR','Diligence jobs could not be stopped',500,{database:error.message});const{error:documentError}=await db.from('documents').update({processing_status:'pending',processed_at:null}).eq('application_id',applicationId).eq('processing_status','processing');if(documentError)throw new AppError('INTERNAL_ERROR','Document processing state could not be reset',500,{database:documentError.message});return data?.length??0;}
  async recoverStaleRunning(staleAfterMs:number):Promise<number>{const db=getServiceClient();const cutoff=new Date(Date.now()-staleAfterMs).toISOString();const{data,error}=await db.from('processing_jobs').update({status:'pending',started_at:null,completed_at:null,error_message:'Recovered after the previous worker stopped unexpectedly'}).eq('status','running').lt('started_at',cutoff).select('application_id');if(error)throw new AppError('INTERNAL_ERROR','Interrupted jobs could not be recovered',500,{database:error.message});const applicationIds=[...new Set((data??[]).map((job)=>job.application_id))];if(applicationIds.length){const{error:documentError}=await db.from('documents').update({processing_status:'pending',processed_at:null}).in('application_id',applicationIds).eq('processing_status','processing');if(documentError)throw new AppError('INTERNAL_ERROR','Interrupted document states could not be recovered',500,{database:documentError.message});}return data?.length??0;}
  async fail(job: ProcessingJobRow, error: unknown, maxRetries: number, retryable: boolean):Promise<'pending'|'failed'>{const message=error instanceof Error?error.message.slice(0,2000):'Unknown job failure';if(retryable&&job.retry_count<maxRetries){const retryCount=job.retry_count+1;const next=new Date(Date.now()+retryDelayMs(retryCount,error)).toISOString();await getServiceClient().from('processing_jobs').update({status:'pending',retry_count:retryCount,error_message:message,payload:{...((job.payload as Record<string,Json>)??{}),next_attempt_at:next}}).eq('id',job.id);return'pending';}await getServiceClient().from('processing_jobs').update({status:'failed',error_message:message,completed_at:new Date().toISOString()}).eq('id',job.id);return'failed';}
  async nextPendingDelayMs():Promise<number|null>{const{data}=await getServiceClient().from('processing_jobs').select('payload').eq('status','pending').limit(100);if(!data?.length)return null;const now=Date.now();return Math.max(0,Math.min(...data.map((row)=>{const payload=(row.payload??{})as Record<string,Json>;const timestamp=typeof payload.next_attempt_at==='string'?Date.parse(payload.next_attempt_at):now;return Number.isFinite(timestamp)?timestamp-now:0;})));}
  async retry(id: string) { const db = getServiceClient(); const { data: job } = await db.from('processing_jobs').select('*').eq('id', id).single(); if (!job) throw new AppError('NOT_FOUND', 'Job not found', 404); if (job.status !== 'failed') throw new AppError('CONFLICT', 'Only failed jobs can be retried', 409); await db.from('processing_jobs').update({ status: 'pending', error_message: null, completed_at: null }).eq('id', id); return { ...job, status: 'pending' as const }; }
}
