import {beforeEach,describe,expect,it,vi} from 'vitest';
import {z} from 'zod';
import {AppError} from '../../lib/errors.js';
import {resetEnvForTests} from '../../lib/env.js';
import type {AIProvider} from '../../ai/provider.js';
import {ProviderCircuitBreaker,ResilientAIProvider} from '../../ai/resilient-provider.js';
const input={model:'primary',systemPrompt:'same system',userPrompt:'same evidence',schema:z.object({value:z.string()}),schemaName:'same-schema',temperature:.1,timeoutMs:1000,metadata:{remainingStageTimeMs:60_000}};
beforeEach(()=>{Object.assign(process.env,{SUPABASE_URL:'http://127.0.0.1:54321',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service',GROQ_API_KEY:'groq',AI_MODEL_FAST:'fast',AI_MODEL_STRONG:'strong',AI_PROVIDER:'groq',TAVILY_API_KEY:'tavily',SEARCH_PROVIDER:'tavily',INTERNAL_WORKER_TOKEN:'a'.repeat(24),AI_FALLBACK_ENABLED:'true',GEMINI_API_KEY:'gemini',AI_FALLBACK_MODEL:'gemini-3.5-flash',AI_FALLBACK_TIMEOUT_MS:'1000',AI_FALLBACK_PERSISTENCE_BUFFER_MS:'1000',AI_MAX_FALLBACK_ATTEMPTS:'1'});resetEnvForTests();});
const result=(provider:string,model:string)=>({data:{value:'ok'},provider,model,latencyMs:1});
describe('resilient AI provider',()=>{
 it('does not invoke Gemini after primary success',async()=>{const primary={generateStructured:vi.fn().mockResolvedValue(result('groq','primary'))};const fallback={generateStructured:vi.fn()};await new ResilientAIProvider(primary as AIProvider,fallback as AIProvider).generateStructured(input);expect(fallback.generateStructured).not.toHaveBeenCalled();});
 it.each([[504,'timeout'],[429,'rate_limit'],[503,'provider_unavailable']])('invokes Gemini exactly once for eligible %s failure',async(status)=>{const primary={generateStructured:vi.fn().mockRejectedValue(new AppError('AI_PROVIDER_ERROR','transient',status, {status},true))};const fallback={generateStructured:vi.fn().mockResolvedValue(result('google','gemini-3.5-flash'))};const output=await new ResilientAIProvider(primary as AIProvider,fallback as AIProvider).generateStructured(input);expect(output.isFallback).toBe(true);expect(fallback.generateStructured).toHaveBeenCalledTimes(1);expect(fallback.generateStructured.mock.calls[0]?.[0]).toMatchObject({systemPrompt:input.systemPrompt,userPrompt:input.userPrompt,schema:input.schema});});
 it('does not fall back for invalid input or authentication errors',async()=>{for(const kind of ['invalid_input','authentication']){const primary={generateStructured:vi.fn().mockRejectedValue(new AppError('AI_PROVIDER_ERROR',kind,400,{kind},false))};const fallback={generateStructured:vi.fn()};await expect(new ResilientAIProvider(primary as AIProvider,fallback as AIProvider).generateStructured(input)).rejects.toThrow();expect(fallback.generateStructured).not.toHaveBeenCalled();}});
 it('does not invoke fallback when the SLA safety budget is exhausted',async()=>{const primary={generateStructured:vi.fn().mockRejectedValue(new AppError('AI_PROVIDER_ERROR','timeout',504,undefined,true))};const fallback={generateStructured:vi.fn()};await expect(new ResilientAIProvider(primary as AIProvider,fallback as AIProvider).generateStructured({...input,metadata:{remainingStageTimeMs:1500}})).rejects.toMatchObject({details:{kind:'sla_exhausted'}});expect(fallback.generateStructured).not.toHaveBeenCalled();});
 it('opens after five transient failures, cools down, and allows one probe',()=>{let now=0;const breaker=new ProviderCircuitBreaker(()=>now);for(let i=0;i<5;i++)breaker.recordTransientFailure();expect(breaker.state()).toBe('open');expect(breaker.allowPrimary()).toBe(false);now=120_001;expect(breaker.state()).toBe('half_open');expect(breaker.allowPrimary()).toBe(true);expect(breaker.allowPrimary()).toBe(false);breaker.recordSuccess();expect(breaker.state()).toBe('closed');});
});
